package:
  name: artiq-kc705-phaser
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch_python: true
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}

requirements:
  build:
    - migen 0.2
    - misoc 0.3
    - llvm-or1k
    - binutils-or1k-linux >=2.27
    - rust-core-or1k
    - cargo
  run:
    - artiq {{ "{tag} py_{number}+git{hash}".format(tag=environ.get("GIT_DESCRIBE_TAG"), number=environ.get("GIT_DESCRIBE_NUMBER"), hash=environ.get("GIT_DESCRIBE_HASH")[1:]) if "GIT_DESCRIBE_TAG" in environ else "" }}

about:
  home: https://m-labs.hk/artiq
  license: GPL
  summary: 'Bitstream, BIOS and runtime for Phaser on the KC705 board'
